config/routes.rb
# == Route Map
#
#                        Prefix Verb   URI Pattern                                       Controller#Action
#                          root GET    /                                                 properties#index
#     users_dissociate_property PATCH  /users/dissociate_property(.:format)              users/registrations#dissociate_property
#              new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#                  user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#          destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#             new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#            edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#                 user_password PATCH  /users/password(.:format)                         devise/passwords#update
#                               PUT    /users/password(.:format)                         devise/passwords#update
#                               POST   /users/password(.:format)                         devise/passwords#create
#      cancel_user_registration GET    /users/cancel(.:format)                           users/registrations#cancel
#         new_user_registration GET    /users/sign_up(.:format)                          users/registrations#new
#        edit_user_registration GET    /users/edit(.:format)                             users/registrations#edit
#             user_registration PATCH  /users(.:format)                                  users/registrations#update
#                               PUT    /users(.:format)                                  users/registrations#update
#                               DELETE /users(.:format)                                  users/registrations#destroy
#                               POST   /users(.:format)                                  users/registrations#create
#         new_user_confirmation GET    /users/confirmation/new(.:format)                 devise/confirmations#new
#             user_confirmation GET    /users/confirmation(.:format)                     devise/confirmations#show
#                               POST   /users/confirmation(.:format)                     devise/confirmations#create
#               new_user_unlock GET    /users/unlock/new(.:format)                       devise/unlocks#new
#                   user_unlock GET    /users/unlock(.:format)                           devise/unlocks#show
#                               POST   /users/unlock(.:format)                           devise/unlocks#create
# current_user_joins_properties PATCH  /properties/current_user_joins(.:format)          properties#current_user_joins
#           property_room_types GET    /properties/:property_id/room_types(.:format)     room_types#index
#                               POST   /properties/:property_id/room_types(.:format)     room_types#create
#        new_property_room_type GET    /properties/:property_id/room_types/new(.:format) room_types#new
#                edit_room_type GET    /room_types/:id/edit(.:format)                    room_types#edit
#                     room_type GET    /room_types/:id(.:format)                         room_types#show
#                               PATCH  /room_types/:id(.:format)                         room_types#update
#                               PUT    /room_types/:id(.:format)                         room_types#update
#                               DELETE /room_types/:id(.:format)                         room_types#destroy
#                property_rooms GET    /properties/:property_id/rooms(.:format)          rooms#index
#                               POST   /properties/:property_id/rooms(.:format)          rooms#create
#             new_property_room GET    /properties/:property_id/rooms/new(.:format)      rooms#new
#                     edit_room GET    /rooms/:id/edit(.:format)                         rooms#edit
#                          room GET    /rooms/:id(.:format)                              rooms#show
#                               PATCH  /rooms/:id(.:format)                              rooms#update
#                               PUT    /rooms/:id(.:format)                              rooms#update
#                               DELETE /rooms/:id(.:format)                              rooms#destroy
#                    properties GET    /properties(.:format)                             properties#index
#                               POST   /properties(.:format)                             properties#create
#                  new_property GET    /properties/new(.:format)                         properties#new
#                 edit_property GET    /properties/:id/edit(.:format)                    properties#edit
#                      property GET    /properties/:id(.:format)                         properties#show
#                               PATCH  /properties/:id(.:format)                         properties#update
#                               PUT    /properties/:id(.:format)                         properties#update
#                               DELETE /properties/:id(.:format)                         properties#destroy
#

Rails.application.routes.draw do
  
	# Guide: 
	# http://www.theodinproject.com/courses/ruby-on-rails/lessons/routing
	
	# Best Practices:
	# https://github.com/bbatsov/rails-style-guide

	# Rails generate:
	# http://railsguides.net/advanced-rails-model-generators/

	# Migration Validations:
	# http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-column

	# Migration:
	# http://api.rubyonrails.org/classes/ActiveRecord/Migration.html

	root 'properties#index'

	devise_scope :user do
		# get "/some/route" => "some_devise_controller"
		# get "signup", to: "devise/registrations#new"
		patch "users/dissociate_property", to: "users/registrations#dissociate_property"
		# patch "users/associate_property/:id"
		# get "users/help", to: "users/registrations#help"
	end
	devise_for :users, :controllers => { 
		registrations: "users/registrations"
	}

	resources :properties do
		# PATCH does a partial update and PUT is used to update the whole resource
		patch 'current_user_joins', on: :collection
		resources :room_types, shallow: true
		resources :rooms, shallow: true
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id          :integer          not null, primary key
#  name        :string
#  access_code :string
#  notes       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Property < ApplicationRecord
	has_one :address, as: :addressable, dependent: :destroy
	has_many :users
	has_many :room_types

	validates :name, presence: true
	validates :access_code, presence: true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    if (current_user.property == nil)
      @properties = Property.all
    else
      redirect_to current_user.property
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @address = @property.address

    # For displaying all users
    @users = @property.users

    # For displaying all room types
    @room_types = @property.room_types
  end

  # GET /properties/new
  def new
    @address = Address.new
    @address.address1 = Faker::Address.street_address
    @address.city = Faker::Address.city
    @address.state = Faker::Address.state
    @address.zip = Faker::Address.zip
    @address.country = Faker::Address.country
    @address.phone = Faker::PhoneNumber.cell_phone
    
    @property = Property.new
    @property.name = Faker::Company.name
  end

  # GET /properties/1/edit
  def edit
    @address = @property.address
  end

  # POST /properties
  # POST /properties.json
  def create
    # Save the address
    @address = Address.new(address_params)
    if @address.save
      puts "Address Created by #{current_user}"
    else
      # Address couldn't be saved
      flash[:alert] = "Address couldn't be saved"
      redirect_to new_property_url
      return
    end

    # Save the property
    @property = Property.new(property_params)
    @property.access_code = SecureRandom.hex(3)
    @property.address = @address

    if @property.save
      # set the current user's property
      current_user.property_id = @property.id
      current_user.save
      redirect_to properties_url, notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /properties/current_user_joins
  def current_user_joins
    # if current user already belongs to a property
    if (current_user.property != nil)
      redirect_to current_user.property
      return
    end
    
    # get property id from params
    pid = params[:user][:property_id].to_i

    # http://stackoverflow.com/questions/1017210/rails-flash-message-remains-for-two-page-loads
    
    # if property id is 0 or null
    if ((pid == nil) || (pid == 0))
      flash.now[:error] = "Property not selected or does not exist"
      render "index"
      return
    end

    # check access code
    if (Property.find(pid).access_code == params[:access_code])
      current_user.property_id = pid
    else
      flash.now[:error] = "Access Code does not match"
      render "index"
      return
    end

    # save current user
    if (current_user.save)
      redirect_to current_user.property, notice: "Joined property"
    else
      flash.now[:error] = "Could not join property"
      render "index"
      return
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :notes)
    end

    def address_params
      params.require(:address).permit(:address1, :address2, :city, :state, :zip, :country, :phone, :fax, :email)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<!-- Needs property and @address -->

<%= form_for(property) do |f| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <!-- http://apidock.com/rails/ActionView/Helpers/FormHelper/fields_for -->
  <!-- http://stackoverflow.com/questions/892624/how-to-handle-multiple-models-in-a-rails-form -->
  <!-- http://theartandscienceofruby.com/2015/08/20/multiple-models-in-a-single-form/ -->
  <%= fields_for @address do |fa| %>
    <div class="field">
      <%= fa.label :address1 %>
      <%= fa.text_field :address1 %>
    </div>
    <div class="field">
      <%= fa.label :address2 %>
      <%= fa.text_field :address2 %>
    </div>
    <div class="field">
      <%= fa.label :city %>
      <%= fa.text_field :city %>
    </div>
    <div class="field">
      <%= fa.label :state %>
      <%= fa.text_field :state %>
    </div>
    <div class="field">
      <%= fa.label :zip %>
      <%= fa.text_field :zip %>
    </div>
    <div class="field">
      <%= fa.label :country %>
      <%= fa.text_field :country %>
    </div>
    <div class="field">
      <%= fa.label :phone %>
      <%= fa.text_field :phone %>
    </div>
    <div class="field">
      <%= fa.label :fax %>
      <%= fa.text_field :fax %>
    </div>
    <div class="field">
      <%= fa.label :email %>
      <%= fa.text_field :email %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Cancel', @property %>

app/views/properties/index.html.erb
<!-- This page is shown only when current_user does not belong to any property -->
<h1>Join Property</h1>

<%= form_for current_user, url: current_user_joins_properties_path, method: :patch do |f| %>
  <div class="field">
    <%= f.label :property_id %>
    <%= f.collection_select(:property_id, Property.all, :id, :name, {include_blank: true }) %>
  </div>
  <div class="field">
    <%= label_tag :access_code %> <br>
    <%= text_field_tag :access_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br>
<div class="new-property-form-container"></div>
<%= link_to 'New Property', new_property_path, remote: true, class: "new-property-link" %>

app/views/properties/new.js.erb
// Needs @property and @address

// Functions
// https://www.sitepoint.com/5-ways-declare-functions-jquery/

// Hide the new property link
$("a.new-property-link").hide();

// Display the form container
$("div.new-property-form-container").empty();
$("div.new-property-form-container").show();

// Insert the _form.html.erb partial
$("div.new-property-form-container").append('<%= j( render(partial: "form", locals: {property: @property, address: @address}) ) %>');

// Executes when cancel is clicked
function hideNewPropertyFormContainer() {
	$("div.new-property-form-container").empty();
	$("div.new-property-form-container").hide();
	$("a.new-property-link").show();
}
// Insert the cancel button
$("div.new-property-form-container").append('<a href="javascript:void(0);" onclick="hideNewPropertyFormContainer()">Cancel</a>');

app/views/properties/show.html.erb
<h1>Property Settings</h1>

<h2>Details</h2>
<p>
  <strong>Name:</strong>
  <%= @property.name %>
  <br>
  <% if (@address != nil) %>
    <strong>Address 1:</strong>
    <%= @address.address1 %>
    <br>
    <strong>Address 2:</strong>
    <%= @address.address2 %>
    <br>
    <strong>City:</strong>
    <%= @address.city %>
    <br>
    <strong>State:</strong>
    <%= @address.state %>
    <br>
    <strong>Zip:</strong>
    <%= @address.zip %>
    <br>
    <strong>Country:</strong>
    <%= @address.country %>
    <br>
    <strong>Phone:</strong>
    <%= @address.phone %>
    <br>
  <% end %>

  <strong>Access code:</strong>
  <%= @property.access_code %>
  <br>
  <strong>Notes:</strong>
  <%= @property.notes %>
  <br>
  <%= link_to 'Edit Property', edit_property_path(@property) %>
</p>

<h2>Room Types</h2>
<table class="room-types">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @room_types.each do |room_type| %>
      <%= render room_type, room_type: room_type %>
    <% end %>
  </tbody>
</table>

<div class="new_room_type_form_container"></div>
<%= link_to 'New Room Type', new_property_room_type_path(@property), remote: true, class: "new_room_type_link" %>

<h2>Users</h2>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.firstname %> <%= user.lastname %> <%= user.username %> (<%= user.email %>) 
      <%= link_to "Remove", users_dissociate_property_path(:user => {:id => user.id} ), :method => :patch, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>