config/routes.rb
# == Route Map
#
#                        Prefix Verb   URI Pattern                                       Controller#Action
#                          root GET    /                                                 properties#index
#     users_dissociate_property PATCH  /users/dissociate_property(.:format)              users/registrations#dissociate_property
#              new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#                  user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#          destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#             new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#            edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#                 user_password PATCH  /users/password(.:format)                         devise/passwords#update
#                               PUT    /users/password(.:format)                         devise/passwords#update
#                               POST   /users/password(.:format)                         devise/passwords#create
#      cancel_user_registration GET    /users/cancel(.:format)                           users/registrations#cancel
#         new_user_registration GET    /users/sign_up(.:format)                          users/registrations#new
#        edit_user_registration GET    /users/edit(.:format)                             users/registrations#edit
#             user_registration PATCH  /users(.:format)                                  users/registrations#update
#                               PUT    /users(.:format)                                  users/registrations#update
#                               DELETE /users(.:format)                                  users/registrations#destroy
#                               POST   /users(.:format)                                  users/registrations#create
#         new_user_confirmation GET    /users/confirmation/new(.:format)                 devise/confirmations#new
#             user_confirmation GET    /users/confirmation(.:format)                     devise/confirmations#show
#                               POST   /users/confirmation(.:format)                     devise/confirmations#create
#               new_user_unlock GET    /users/unlock/new(.:format)                       devise/unlocks#new
#                   user_unlock GET    /users/unlock(.:format)                           devise/unlocks#show
#                               POST   /users/unlock(.:format)                           devise/unlocks#create
# current_user_joins_properties PATCH  /properties/current_user_joins(.:format)          properties#current_user_joins
#           property_room_types GET    /properties/:property_id/room_types(.:format)     room_types#index
#                               POST   /properties/:property_id/room_types(.:format)     room_types#create
#        new_property_room_type GET    /properties/:property_id/room_types/new(.:format) room_types#new
#                edit_room_type GET    /room_types/:id/edit(.:format)                    room_types#edit
#                     room_type GET    /room_types/:id(.:format)                         room_types#show
#                               PATCH  /room_types/:id(.:format)                         room_types#update
#                               PUT    /room_types/:id(.:format)                         room_types#update
#                               DELETE /room_types/:id(.:format)                         room_types#destroy
#                property_rooms GET    /properties/:property_id/rooms(.:format)          rooms#index
#                               POST   /properties/:property_id/rooms(.:format)          rooms#create
#             new_property_room GET    /properties/:property_id/rooms/new(.:format)      rooms#new
#                     edit_room GET    /rooms/:id/edit(.:format)                         rooms#edit
#                          room GET    /rooms/:id(.:format)                              rooms#show
#                               PATCH  /rooms/:id(.:format)                              rooms#update
#                               PUT    /rooms/:id(.:format)                              rooms#update
#                               DELETE /rooms/:id(.:format)                              rooms#destroy
#                    properties GET    /properties(.:format)                             properties#index
#                               POST   /properties(.:format)                             properties#create
#                  new_property GET    /properties/new(.:format)                         properties#new
#                 edit_property GET    /properties/:id/edit(.:format)                    properties#edit
#                      property GET    /properties/:id(.:format)                         properties#show
#                               PATCH  /properties/:id(.:format)                         properties#update
#                               PUT    /properties/:id(.:format)                         properties#update
#                               DELETE /properties/:id(.:format)                         properties#destroy
#

Rails.application.routes.draw do
  
	# Guide: 
	# http://www.theodinproject.com/courses/ruby-on-rails/lessons/routing
	
	# Best Practices:
	# https://github.com/bbatsov/rails-style-guide

	# Rails generate:
	# http://railsguides.net/advanced-rails-model-generators/

	# Migration Validations:
	# http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-column

	# Migration:
	# http://api.rubyonrails.org/classes/ActiveRecord/Migration.html

	root 'properties#index'

	devise_scope :user do
		# get "/some/route" => "some_devise_controller"
		# get "signup", to: "devise/registrations#new"
		patch "users/dissociate_property", to: "users/registrations#dissociate_property"
		# patch "users/associate_property/:id"
		# get "users/help", to: "users/registrations#help"
	end
	devise_for :users, :controllers => { 
		registrations: "users/registrations"
	}

	resources :properties do
		# PATCH does a partial update and PUT is used to update the whole resource
		patch 'current_user_joins', on: :collection
		resources :room_types, shallow: true
		resources :rooms, shallow: true
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController
  before_action :set_room_type, only: [:edit, :update, :destroy]

  # GET /properties/:property_id/room_types/new(.:format)
  def new
    @room_type = RoomType.new
    @property = Property.find(params[:property_id])

    # Fake Values
    @room_type.name = Faker::Beer.name
    @room_type.code = @room_type.name[0, 2] + SecureRandom.hex(1).to_s
    @room_type.description = Faker::Beer.style
  end

  # GET /room_types/1/edit
  def edit
    @property = @room_type.property
  end

  # POST /properties/:property_id/room_types(.:format)
  # create.js.erb
  def create
    # TODO: Check if Property exists

    @room_type = RoomType.new(room_type_params)
    @room_type.property_id = params[:property_id].to_i
    @room_type.save

  end

  # PATCH/PUT /room_types/1
  def update
    @room_type.update(room_type_params)
    # notice: 'Room type was successfully updated.'
  end

  # DELETE /room_types/1
  # DELETE /room_types/1.json
  def destroy
    @room_type.destroy
    # notice: 'Room type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_type
      @room_type = RoomType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_type_params
      params.require(:room_type).permit(:name, :code, :description)
    end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/room_types/_form.html.erb
<!-- Needs property and room_type -->
<!-- property set to nil for edit -->
<%= form_for([property, room_type], remote: true) do |f| %>
  <% if room_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room_type.errors.count, "error") %> prohibited this room_type from being saved:</h2>

      <ul>
      <% room_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %> | 
    <% if room_type.id.nil? %>
      <a id="new_room_type_cancel" href="javascript:void(0);" onclick="hideNewRoomTypeFormContainer()">Cancel</a>
    <% else %>
      <a id="<%= dom_id(room_type) %>_cancel" href="javascript:void(0);" onclick="hideEditRoomTypeForm('<%= dom_id(room_type) %>')">Cancel</a>
    <% end %>
  </div>
<% end %>

app/views/room_types/_form_errors.html.erb
<!-- Requires: room_type -->

<% if room_type.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(room_type.errors.count, "error") %> prohibited this room_type from being saved:</h2>

    <ul>
    <% room_type.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/room_types/_room_type.html.erb
<!-- Needs room_type -->
<%= content_tag_for(:tr, room_type) do %>
  <td><%= room_type.code %></td>
  <td><%= room_type.name %></td>
  <td><%= room_type.description %></td>
  <td><%= link_to 'Edit', edit_room_type_path(room_type), remote: true %></td>
  <td><%= link_to 'Destroy', room_type, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/room_types/create.js.erb
// Inserts the newly created room type into the DOM
// Needs @room_type
var $form_container = $("div.new_room_type_form_container");
var $new_link = $("a.new_room_type_link");
var $form = $("form#new_room_type");
var $tbody = $("table.room-types tbody");

<% if @room_type.errors.any? %>
	// @room_type did not save, display errors
	$form.prepend('<%= j( render(partial: "form_errors", locals: {room_type: @room_type}) ) %>');
<% else %>
	// @room_type successfully saved, display the new room type
	$tbody.append('<%= j(render @room_type, room_type: @room_type) %>');

	// Clear the form container
	$form_container.empty();
	// Hide the form container
	$form_container.hide();
	// Show the new link
	$new_link.show();
<% end %>

app/views/room_types/destroy.js.erb
// Requires: @room_type
$row = $("tr#<%= dom_id(@room_type) %>");
$row.remove();

app/views/room_types/edit.js.erb
// Requires: @room_type

$row = $("tr#<%= dom_id(@room_type) %>");

// Replace contents of the table row
$row.empty();
$row.append('<td colspan="5"></td>');

$form_container = $("tr#<%= dom_id(@room_type) %> td");

$form_container.append("<h3>Edit Room Type</h3>");
// Insert the form
$form_container.append('<%= j( render(partial: "form", locals: {property: nil, room_type: @room_type}) ) %>');


// Cancel link function
function hideEditRoomTypeForm(id) {
	alert(id);

	$row = $("tr#" + id);
	// Clear the row
	$row.empty();

	// Display @room_type in the row
	$row.replaceWith('<%= j(render @room_type, room_type: @room_type) %>');
}

app/views/room_types/new.js.erb
// This runs when new is clicked
// Hide the new room type link

var $form_container = $("div.new_room_type_form_container");
var $new_link = $("a.new_room_type_link");

// Hide the new link
$new_link.hide();

// Clear the form container
$form_container.empty();
// Display the form continer
$form_container.show();
// Insert the _form.html.erb partial inside the form container
$form_container.append('<%= j( render(partial: "form", locals: {property: @property, room_type: @room_type}) ) %>');

// Cancel link function
function hideNewRoomTypeFormContainer() {
	// Clear the form container
	$form_container.empty();
	// Hide the form container
	$form_container.hide();
	// Show the new link
	$new_link.show();
}

app/views/room_types/update.js.erb
// Updates @room_type
// Requires: @room_type
var $form = $("form#<%= dom_id(@room_type, :edit) %>");
var $row = $("tr#<%= dom_id(@room_type) %>");
<% if @room_type.errors.any? %>
	// @room_type did not save, display errors
	$form.prepend('<%= j( render(partial: "form_errors", locals: {room_type: @room_type}) ) %>');
<% else %>
	// @room_type saved, hide the form and display the updated row
	$row.empty();
	$row.replaceWith('<%= j(render @room_type, room_type: @room_type) %>');
<% end %>