config/routes.rb
# == Route Map
#
#                        Prefix Verb   URI Pattern                                       Controller#Action
#                          root GET    /                                                 properties#index
#     users_dissociate_property PATCH  /users/dissociate_property(.:format)              users/registrations#dissociate_property
#              new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#                  user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#          destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#             new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#            edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#                 user_password PATCH  /users/password(.:format)                         devise/passwords#update
#                               PUT    /users/password(.:format)                         devise/passwords#update
#                               POST   /users/password(.:format)                         devise/passwords#create
#      cancel_user_registration GET    /users/cancel(.:format)                           users/registrations#cancel
#         new_user_registration GET    /users/sign_up(.:format)                          users/registrations#new
#        edit_user_registration GET    /users/edit(.:format)                             users/registrations#edit
#             user_registration PATCH  /users(.:format)                                  users/registrations#update
#                               PUT    /users(.:format)                                  users/registrations#update
#                               DELETE /users(.:format)                                  users/registrations#destroy
#                               POST   /users(.:format)                                  users/registrations#create
#         new_user_confirmation GET    /users/confirmation/new(.:format)                 devise/confirmations#new
#             user_confirmation GET    /users/confirmation(.:format)                     devise/confirmations#show
#                               POST   /users/confirmation(.:format)                     devise/confirmations#create
#               new_user_unlock GET    /users/unlock/new(.:format)                       devise/unlocks#new
#                   user_unlock GET    /users/unlock(.:format)                           devise/unlocks#show
#                               POST   /users/unlock(.:format)                           devise/unlocks#create
# current_user_joins_properties PATCH  /properties/current_user_joins(.:format)          properties#current_user_joins
#           property_room_types GET    /properties/:property_id/room_types(.:format)     room_types#index
#                               POST   /properties/:property_id/room_types(.:format)     room_types#create
#        new_property_room_type GET    /properties/:property_id/room_types/new(.:format) room_types#new
#                edit_room_type GET    /room_types/:id/edit(.:format)                    room_types#edit
#                     room_type GET    /room_types/:id(.:format)                         room_types#show
#                               PATCH  /room_types/:id(.:format)                         room_types#update
#                               PUT    /room_types/:id(.:format)                         room_types#update
#                               DELETE /room_types/:id(.:format)                         room_types#destroy
#                property_rooms GET    /properties/:property_id/rooms(.:format)          rooms#index
#                               POST   /properties/:property_id/rooms(.:format)          rooms#create
#             new_property_room GET    /properties/:property_id/rooms/new(.:format)      rooms#new
#                     edit_room GET    /rooms/:id/edit(.:format)                         rooms#edit
#                          room GET    /rooms/:id(.:format)                              rooms#show
#                               PATCH  /rooms/:id(.:format)                              rooms#update
#                               PUT    /rooms/:id(.:format)                              rooms#update
#                               DELETE /rooms/:id(.:format)                              rooms#destroy
#                    properties GET    /properties(.:format)                             properties#index
#                               POST   /properties(.:format)                             properties#create
#                  new_property GET    /properties/new(.:format)                         properties#new
#                 edit_property GET    /properties/:id/edit(.:format)                    properties#edit
#                      property GET    /properties/:id(.:format)                         properties#show
#                               PATCH  /properties/:id(.:format)                         properties#update
#                               PUT    /properties/:id(.:format)                         properties#update
#                               DELETE /properties/:id(.:format)                         properties#destroy
#

Rails.application.routes.draw do
  
	# Guide: 
	# http://www.theodinproject.com/courses/ruby-on-rails/lessons/routing
	
	# Best Practices:
	# https://github.com/bbatsov/rails-style-guide

	# Rails generate:
	# http://railsguides.net/advanced-rails-model-generators/

	# Migration Validations:
	# http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-column

	# Migration:
	# http://api.rubyonrails.org/classes/ActiveRecord/Migration.html

	root 'properties#index'

	devise_scope :user do
		# get "/some/route" => "some_devise_controller"
		# get "signup", to: "devise/registrations#new"
		patch "users/dissociate_property", to: "users/registrations#dissociate_property"
		# patch "users/associate_property/:id"
		# get "users/help", to: "users/registrations#help"
	end
	devise_for :users, :controllers => { 
		registrations: "users/registrations"
	}

	resources :properties do
		# PATCH does a partial update and PUT is used to update the whole resource
		patch 'current_user_joins', on: :collection
		resources :room_types, shallow: true
		resources :rooms, shallow: true
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id           :integer          not null, primary key
#  room_number  :integer          not null
#  location     :string
#  vacant       :boolean          default("t"), not null
#  clean        :boolean          default("t"), not null
#  inventory    :boolean          default("t"), not null
#  room_type_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Room < ApplicationRecord
  belongs_to :room_type
  after_initialize :default_values

  validates :room_number, presence: true
  validates :vacant, presence: true 
  validates :clean, presence: true
  validates :inventory, presence: true

  # TODO: Might remove this method
  def default_values
  	if (self.vacant.nil?)
  		self.vacant = true
  	end
  	if (self.clean.nil?)
  		self.clean = true
  	end
  	if (self.inventory.nil?)
  		self.inventory = true
  	end
  end
end

app/models/room_type.rb
# == Schema Information
#
# Table name: room_types
#
#  id          :integer          not null, primary key
#  name        :string
#  code        :string(4)
#  description :string
#  property_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class RoomType < ApplicationRecord
  belongs_to :property
  has_many :rooms
  before_save :convert_code_to_upper_case

  validates :name, presence: true
  validates :code, presence: true, :length => { :maximum => 4 }
  validates :description, presence: true

  private
  def convert_code_to_upper_case
  	self.code.upcase!
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_number, :location, :vacant, :clean, :inventory, :room_type_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<!-- Requires: property, room -->
<% if room.new_record? %>
  <h2>New Room</h2>
<% else %>
  <h2>Edit Room</h2>
<% end %>
<%= form_for([property, room], remote: true) do |f| %>
  
  <div class="field">
    <%= f.label :room_number %>
    <%= f.number_field :room_number %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <% if !room.new_record? %>
    <div class="field">
      <%= f.label :vacant %>
      <%= f.check_box :vacant %>
    </div>

    <div class="field">
      <%= f.label :clean %>
      <%= f.check_box :clean %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inventory %>
    <%= f.check_box :inventory %>
  </div>

  <div class="field">
    <%= f.label :room_type_id %>
    <%= f.collection_select(:room_type_id, property.room_types, :id, :dd_label, {include_blank: false }) %>

  </div>

  <div class="actions">
    <%= f.submit %> | 
    <% if room.new_record? %>
      <a id="new_room_cancel" href="javascript:void(0);" onclick="hideNewRoomFormContainer()">Cancel</a>
    <% else %>
      <a id="<%= dom_id(room) %>_cancel" href="javascript:void(0);" onclick="hideEditRoomForm('<%= dom_id(room) %>')">Cancel</a>
    <% end %>
  </div>
<% end %>

app/views/rooms/_form_errors.html.erb
<!-- Requires: room -->

<% if room.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

    <ul>
    <% room.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<!-- Requires: room -->
<%= content_tag_for(:tr, room) do %>
  <td><%= room.room_number %></td>
  <td><%= room.location %></td>
  <td><%= room.vacant %></td>
  <td><%= room.clean %></td>
  <td><%= room.inventory %></td>
  <td><%= room.room_type.code %></td>
  <td><%= link_to 'Show', room %></td>
  <td><%= link_to 'Edit', edit_room_path(room) %></td>
  <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room number</th>
      <th>Location</th>
      <th>Vacant</th>
      <th>Clean</th>
      <th>Inventory</th>
      <th>Room type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_number %></td>
        <td><%= room.location %></td>
        <td><%= room.vacant %></td>
        <td><%= room.clean %></td>
        <td><%= room.inventory %></td>
        <td><%= room.room_type %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/new.js.erb
// This runs when new is clicked
// Hide the new room link
// Requires: @property, @room

var $form_container = $("#new_room_form_container");
var $new_link = $("#new_room_link");

// Hide the new link
$new_link.hide();

// Clear the form container
$form_container.empty();
// Display the form continer
$form_container.show();
// Insert the _form.html.erb partial inside the form container
$form_container.append('<%= j( render(partial: "form", locals: {property: @property, room: @room}) ) %>');

// Cancel link function
function hideNewRoomFormContainer() {
	// Clear the form container
	$form_container.empty();
	// Hide the form container
	$form_container.hide();
	// Show the new link
	$new_link.show();
}

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room number:</strong>
  <%= @room.room_number %>
</p>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<p>
  <strong>Vacant:</strong>
  <%= @room.vacant %>
</p>

<p>
  <strong>Clean:</strong>
  <%= @room.clean %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @room.inventory %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @room.room_type %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>